name: Docker Image CI


on:
  workflow_dispatch:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: export image
      run: mkdir staging && docker save -o staging/my-image-name.tar my-image-name
    - uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: staging
      
